- Added Review System
develhope/Java27-progetto3-team2 pull request #96
Opened 2024-11-16 09:05 UTC by Fabio013

2024-11-16 10:57 UTC, DonatoAletta approved these changes

2024-11-16 14:08 UTC, DonatoAletta requested changes

2024-11-16 14:08 UTC, DonatoAletta commented on src/main/java/com/develhope/Java27_progetto3_team2/review/controller/ReviewController.java
> +
Mancano altre CRUD

2024-11-19 11:00 UTC, Fabio013 commented on src/main/java/com/develhope/Java27_progetto3_team2/review/controller/ReviewController.java
> +
Ho creato altre CRUD, a breve valuto rapidamente eccezioni e log ed aggiorno la PR

2024-11-19 23:25 UTC, Fabio013 commented on src/main/java/com/develhope/Java27_progetto3_team2/review/controller/ReviewController.java
> +
Aggiunti metodi CRUD di principale utilità,
log, eccezioni e alcune ottimizzazioni del codice.
Aggiornata la PR

2024-11-20 10:37 UTC, DonatoAletta approved these changes

2024-11-20 14:59 UTC, merged